# Generated by Django 3.0.7 on 2020-08-30 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('food_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('food_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('food_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('food_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('food_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('food_photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('food_photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('owner', models.CharField(max_length=200)),
                ('igredients', models.CharField(blank=True, max_length=1000)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
