# Generated by Django 3.0.7 on 2020-08-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='igredients',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
