# Generated by Django 3.0.7 on 2020-08-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20200830_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
