# Generated by Django 3.0.7 on 2020-08-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='igredients',
            field=models.CharField(choices=[('Sourdough', 'Sourdough'), ('Tumeric', 'Tumeric'), ('Cinnammon', 'Cinnammon'), ('Parsley', 'Parsley'), ('Chicken Foot', 'Chicken Foot'), ('Love', 'Love'), ('Sativa', 'Sativa'), ('Gluten Free', 'Gluten Free')], max_length=1000),
        ),
    ]
