# Generated by Django 3.0.7 on 2020-08-31 03:02

import ckeditor.fields
from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20200830_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='igredients',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sourdough', 'Sourdough'), ('Tumeric', 'Tumeric'), ('Cinnammon', 'Cinnammon'), ('Parsley', 'Parsley'), ('Chicken Foot', 'Chicken Foot'), ('Love', 'Love'), ('Sativa', 'Sativa'), ('Gluten Free', 'Gluten Free')], max_length=72),
        ),
    ]
