# Generated by Django 3.0.7 on 2020-08-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20200830_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_for_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
