# Generated by Django 3.0.7 on 2020-09-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_auto_20200906_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='food_photo',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
