# Generated by Django 3.0.7 on 2020-09-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0015_auto_20200906_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='user_id',
        ),
    ]
