# Generated by Django 3.0.7 on 2020-09-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0016_remove_food_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_for_slider2',
            field=models.BooleanField(default=False),
        ),
    ]
