# Generated by Django 3.0.7 on 2020-09-07 03:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_food_is_for_slider2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='igredients',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sourdough', 'Sourdough'), ('Chocolate Chips', 'Chocolate Chips'), ('Biscuit Dough', 'Biscuit Dough'), ('Penaut Butter', 'Penaut Butter'), ('Almond Butter', 'Almond Butter'), ('Rice Krispies', 'Rice Krispies'), ('Macarpone Cream', 'Macarpone Cream'), ('Cinnammon', 'Cinnammon'), ('Espresso', 'Espresso'), ('Baking Powder', 'Baking Powder'), ('Baking Soda', 'Baking Soda'), ('Vanilla Ice Cream', 'Vanilla Ice Cream'), ('Sprinkles', 'Sprinkles'), ('Coconut Flakes', 'Coconut Flakes'), ('Coconut Oil', 'Coconut Oil'), ('Vanilla Extract', 'Vanilla Extract'), ('Bananas', 'Bananas'), ('Oats', 'Oats'), ('Eggs', 'Eggs'), ('BlueBerry', 'Blueberry'), ('Carrots', 'Carrots'), ('Scoth Bonnet', 'Scoth Bonnet'), ('Custard', 'Custard'), ('Apples', 'Apples'), ('Pumkin', 'Pumkin'), ('Basil', 'Basil'), ('Cheese', 'Cheese'), ('Cornstarch', 'Cornstarch'), ('Tequila', 'Tequila'), ('Limes', 'Limes'), ('Milk', 'Milk'), ('Whole Milk', 'Whole Milk'), ('Skim Milk', 'Skim Milk'), ('Almond Milk', 'Almond Milk'), ('Food Coloring', 'Food Coloring'), ('Pecans', 'Pecans'), ('Avocados', 'Avocados'), ('Maple Syrup', 'Maple Syrup'), ('Taco Shells', 'Taco Shells'), ('Minced Beef', 'Minced Beef'), ('Pork Roast', 'Pork Roast'), ('Pork Chops', 'Pork Chops'), ('Pork Belly', 'Pork Belly'), ('Pork Tenderloin', 'Pork Tenderloin'), ('Pork Ribs', 'Pork Ribs'), ('Beef Ribs', 'Beef Ribs'), ('Potato', 'Potato'), ('Sliced Ham', 'Sliced Ham'), ('Breadcrumbs', 'Breadcrumbs'), ('Honey', 'Honey'), ('Cream Cheese', 'Cream Cheese'), ('Olive Oil', 'Olive Oil'), ('Mozzarella', 'Mozzarella'), ('Red Pepper Flakes', 'Red Pepper Flakes'), ('Ground Black Pepper', 'Ground Black Pepper'), ('Garlic', 'Garlic'), ('Ginger', 'Ginger'), ('Thyme', 'Thyme'), ('Cumin', 'Cumin'), ('Onion', 'Onion'), ('Tomatoes', 'Tomatoes'), ('Crushed Tomatoes', 'Crushed Tomatoes'), ('Jalapeño', 'Jalapeño'), ('Brie', 'Brie'), ('Gouda', 'Gouda'), ('Provolone', 'Provolone'), ('Parmasean', 'Parmasean'), ('Feta', 'Feta'), ('Cheese Mix', 'Cheese Mix'), ('Bell Peppers', 'Bell Peppers'), ('Tortilla', 'Tortilla'), ('Baguettes', 'Baguettes'), ('Sweet Potato', 'Sweet Potato'), ('Condensed Milk', 'Condensed Milk'), ('Heavy Cream', 'Heavy Cream'), ('Wafer Cookies', 'Wafer Cookies'), ('Sugar', 'Sugar'), ('Salt', 'Salt'), ('Walnuts', 'Walnuts'), ('Granola', 'Granola'), ('Parsley', 'Parsley'), ('Chicken Breast', 'Chicken Breast'), ('Chicken Thigh', 'Chicken Thigh'), ('Chicken Legs', 'Chicken Legs'), ('Chicken Wings', 'Chicken Wings'), ('Oysters', 'Oysters'), ('Shrimp', 'Shrimp'), ('Salmon', 'Salmon'), ('Icing Sugar', 'Icing Sugar'), ('Lemons', 'Lemons'), ('Fondant', 'Fondant'), ('Tumeric', 'Tumeric'), ('Edible Flowers', 'Edible Flowers'), ('All Purpose Flour', 'All Purpose Flour'), ('Whole Wheat Flour', 'Whole Wheat Flour'), ('Cake Flour', 'Cake Flour'), ('Pastry Flour', 'Pastry Flour'), ('Almond Flour', 'Almond Flour'), ('Butter', 'Butter'), ('Sativa', 'Sativa'), ('Gluten Free Flour', 'Gluten Free Flour'), ('Basmati Rice', ' Basmati Rice'), ('White Rice', ' White Rice'), ('Whole Wheat Rice', ' Whole Wheat Rice'), ('Spaghetti', ' Spaghetti'), ('Rice', ' Rice'), ('Ham', ' Ham'), ('Jamón ibérico', ' Jamón ibérico'), ('Thai Green Curry Paste', ' Thai Green Curry Paste'), ('Raisins', 'Raisins')], max_length=1176),
        ),
    ]
