# Generated by Django 3.0.7 on 2020-09-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0019_auto_20200907_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_for_home_page_side',
            field=models.BooleanField(default=False),
        ),
    ]
