# Generated by Django 3.0.7 on 2020-09-07 05:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0020_food_is_for_home_page_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description_short',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
