# Generated by Django 3.0.7 on 2020-09-14 04:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0022_food_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description1',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='food',
            name='description2',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='food',
            name='description3',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='food',
            name='description4',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
