# Generated by Django 3.0.7 on 2020-09-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0023_auto_20200914_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='article_title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
