# Generated by Django 3.0.7 on 2020-09-15 05:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0024_food_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='description3',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='description4',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
