# Generated by Django 3.0.7 on 2020-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0025_auto_20200915_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
