# Generated by Django 3.0.7 on 2020-09-15 02:53

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200829_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ashley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_element', models.CharField(max_length=300)),
                ('years_of_exp', models.IntegerField()),
                ('food_articles', models.IntegerField()),
                ('lifestyle_articles', models.IntegerField()),
                ('customers', models.IntegerField()),
                ('home_page_about', ckeditor.fields.RichTextField()),
                ('about_me_side_bar', ckeditor.fields.RichTextField()),
                ('about_stories2', ckeditor.fields.RichTextField()),
                ('about_short', ckeditor.fields.RichTextField()),
                ('last_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ashley_images_home', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('ashley_images_about1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('ashley_images_about2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('about_side_bar', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
