# Generated by Django 3.0.7 on 2020-09-15 04:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_ashley'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashley',
            name='food_detail_pre_comment',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
