# Generated by Django 3.0.7 on 2020-09-06 22:59

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle_title', models.CharField(max_length=300)),
                ('description', ckeditor.fields.RichTextField()),
                ('lifestyle_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('lifestyle_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('lifestyle_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('lifestyle_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('lifestyle_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('lifestyle_photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('lifestyle_photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('owner', models.CharField(max_length=200)),
                ('is_for_lifestyle_page', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
