# Generated by Django 3.0.7 on 2020-09-06 23:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0002_lifestyle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyle',
            name='description_short',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
