# Generated by Django 3.0.7 on 2020-09-15 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0003_lifestyle_description_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('lifestyle_id', models.IntegerField()),
                ('comments', models.TextField()),
                ('user_id', models.IntegerField(blank=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifestyle_title', models.CharField(default='', editable=False, max_length=300)),
                ('user_id', models.IntegerField()),
                ('life_id', models.IntegerField()),
                ('life_photo', models.ImageField(blank=True, upload_to='')),
                ('life_description', models.TextField(null=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
